### ISSUE TITLE
Is Python 2.6 still a requirement?

### ISSUE THREAD

**Issue by cclauss** [MarkCWirt/MIDIUtil#10]
A dict comprehension is breaking the build on Python 2.6... https://travis-ci.org/MarkCWirt/MIDIUtil/jobs/208221240  This version of Python has not been supported by Python.org since October 2013.  Does MIDIUtil still need to support Python 2.6?

**Comment by MarkCWirt** [comment]
That's a good question. 

I had left support for 2.6 in place in cause there are still some Linux LTS systems which are running 2.6, but at this point I'm not sure if any of the common distributions still run 2.6 or not.

Currently 2.6 isn't working, owning to the change you made to `removeDuplicates()`. (By the way, I had to roll out the changes you made de-interleaving function, as it was causing the code to error on all versions.)

Do you know if 2.6 is in use in any LTS distributions? If not we can remove 2.6 from the travis build. Otherwise we should roll out the `removeDuplicates()` changes you made.

**Comment by MarkCWirt** [comment]
In the interim, I've removed 2.6 from the Travis build file (but I haven't updated any documentation).

**Comment by cclauss** [comment]
I think that dropping 2.6 is the right way to go.

The pep8 stuff is trivial to do if you get a free editor like https://atom.io and add the https://atom.io/packages/linter-flake8 package.

**Comment by MarkCWirt** [comment]
I use atom for writing ReStructuredText, but I haven't really done any coding with it. For coding I'm ususally inside [spyder](https://en.wikipedia.org/wiki/Spyder_(software)).

Yea, I'll update the documentation and drop 2.6.  It's not like people are making music on tightly version-controlled embedded systems!

I'll do that as part of a release that I wanted to push out (there are some minor inconsistencies between the dev and release version in terms of using the library, and it's confused at least one user).
