### ISSUE TITLE
Useful to have a constructor using an existing MIDI file?

### ISSUE THREAD

**Issue by TravisTag** [MarkCWirt/MIDIUtil#2]
I know Python doesn't really do multiple argument signatures, but do you think it would be useful to have something like a class function that returns a MIDIFile object given a filehandle of an existing MIDI file opened for reading? It could be useful to be able to open and edit MIDI files that already exist.

I'm already writing a function to do that, just wondering if you'd want it added here on the repo or not.

**Comment by MarkCWirt** [comment]
Travis,

Yes, it could be interesting, and at one point I sketched something out. I have a few thoughts on it, but haven't really done any work.

* The code could parse the file and figure out it's format and number of tracks, instantiating a matching object.
* Once this is done, the most appropriate way for the function to work would be to parse the MIDI file and create `MIDIEvent` objects in `MIDITrack.MIDIEventList`

The interesting thing -- and perhaps the challenge -- is what to do with the `MIDIEvent`s once you have them. Presumably you would be processing this file because you wanted to perform some kind of change or alteration. For example, you would read in a file and then, say, transpose the pitch and/or key of the piece. I think this is where you would decide if the work with worth-while; are there are useful and interesting transformations you could apply to the deconstructed MIDI file?

If you would find use for such a function, and if you can figure out a relatively elegant way of incorporating it into the code, I'd be more than happy to merge a pull request!

(BTW, sorry it's taken a while to get back to you -- things have been pretty busy for me).

**Comment by TravisTag** [comment]
Hi Mark,

So my personal use for this was doing some simple music analysis. Since I was finding music in all kinds of formats, I was trying to use MIDI as an intermediary file-type since it allowed me to easily listen to the pieces as well.

I do think there are probably some interesting transformations as well, I'll think about that. I'll go ahead and fork the repo and try some stuff out!

Thanks,
Travis

**Comment by MarkCWirt** [comment]
Using MIDI as an intermediate file type seems like a reasonable thing to do. Hadn't thought about it from the analysis perspective.
