### ISSUE TITLE
ImportError: cannot import name 'MIDIFile'

### ISSUE THREAD

**Issue by myzinsky** [MarkCWirt/MIDIUtil#8]
I installed MIDIUtil by running:

```bash
pip3.6 install MIDIUtil
```

When I run the example it won't work:

```
Traceback (most recent call last):
  File "sonification.py", line 3, in <module>
    from midiutil import MIDIFile
ImportError: cannot import name 'MIDIFile'
```

**Comment by MarkCWirt** [comment]
I think the issue is that the line you're executing:

    from midiutil import MIDIFile

was taken from the documentation (or README) of the development version of the code, but you've installed version 1.1.1.

For version 1.1.1, you would want to use the format:

    from midiutil.MidiFile import MIDIFile

(a change has been made to simplify the import since 1.1.1 was pushed).

The documentation at http://midiutil.readthedocs.io/en/1.1.1/ should accurately reflect how this version of the library should be used.

I'm going to push a new version to PyPi soon that should make the github README consistent with the operation of the library. I'll leave this ticket open until that happens, in cause someone else is bitten by this.

Thanks for bringing this to my attention!

**Comment by MarkCWirt** [comment]
OK. I pushed a new version -- 1.1.3 -- which should allow for this import format.

It may take a few hours for Pypi to update; you can change your import line or wait a while and install 1.1.3.

Again, thanks for bringing this to my attention.

**Comment by cpoulos** [comment]
Pls Ignore - I figured it out.


"Hi - I'm encountering the same error.  Is it because I'm running Python 3.6?  Is the latest it supports v3.5?"
